### ISSUE TITLE
Issue with hterm.js, in `959a176466ad6dbeced12b019e9fa5b4a08056d2`

### ISSUE THREAD

**Issue by maifeeulasad** [rahmanusta/cloudterm#8]
In the latest pull (959a176466ad6dbeced12b019e9fa5b4a08056d2), it's not rendering anything:
```
properties of undefined (reading 'style')
    at hterm.ScrollPort.setBackgroundColor (hterm.js:9380:18)
    at hterm.Terminal.setBackgroundColor (hterm.js:10908:22)
    at background-color (hterm.js:10571:22)
    at lib.PreferenceManager.notifyChange_ (hterm.js:2120:28)
    at lib.PreferenceManager.notifyAll (hterm.js:2100:14)
    at hterm.Terminal.<anonymous> (hterm.js:10848:21)
hterm.ScrollPort.setBackgroundC
```

Here is a snap:

![image](https://github.com/javaterminal/cloudterm/assets/29339330/0f66bc12-e195-4bde-a28d-8cacfc4791da)

*Maybe I can try to fix it.*

**Comment by maifeeulasad** [comment]
*I was unable to reproduce this in a Linux machine.*

**But this issue persists in Windows machine, till this day.**
